const { SQL_PROMPT_TEMPLATE } = require("../prompts/sqlPrompt");
const { generateSQLFromLLM } = require("../services/aiService");

/**
 * Validates the generated SQL locally to prevent dangerous queries.
 * @param {string} sql 
 * @returns {string|null} - Null if invalid, otherwise the clean SQL.
 */
function localGuardrailsCheck(sql) {
    if (!sql) return null;

    const trimmed = sql.trim();
    const upper = trimmed.toUpperCase();

    // Basic guardrails to match Priyanshu's backend validations
    if (!upper.startsWith("SELECT")) return null;
    if (upper.includes(";")) return null;

    const forbidden = ["DROP", "DELETE", "UPDATE", "ALTER", "INSERT", "TRUNCATE", "EXEC", "MERGE", "CREATE"];
    for (const keyword of forbidden) {
        if (upper.includes(keyword)) return null;
    }

    if (upper.includes("--") || upper.includes("/*")) return null;

    return trimmed;
}

exports.generateSQL = async (req, res) => {
    try {
        const { question } = req.body;

        if (!question) {
            return res.status(400).json({ error: "Question is required." });
        }

        // 1. Build the prompt with the user's question
        const finalPrompt = SQL_PROMPT_TEMPLATE.replace("{user_query}", question);

        // 2. Query Gemini
        const rawSql = await generateSQLFromLLM(finalPrompt);

        // 3. Apply Local Guardrails
        const cleanSql = localGuardrailsCheck(rawSql);

        if (!cleanSql || cleanSql === "SELECT 'INVALID_QUERY' as result") {
            return res.status(400).json({ error: "Unsafe or invalid query generated by AI." });
        }

        // 4. Return to Backend
        res.json({ sql: cleanSql });

    } catch (error) {
        console.error("Controller Error:", error);
        res.status(500).json({ error: "Failed to generate SQL." });
    }
};

const { INSIGHT_PROMPT_TEMPLATE } = require("../prompts/insightPrompt");
const { generateInsightFromLLM } = require("../services/aiService");

exports.generateInsight = async (req, res) => {
    try {
        const { question, data } = req.body;

        if (!question || !data) {
            return res.status(400).json({ error: "Both 'question' and 'data' are required." });
        }

        // 1. Build the prompt
        let finalPrompt = INSIGHT_PROMPT_TEMPLATE.replace("{user_query}", question);
        finalPrompt = finalPrompt.replace("{json_data}", JSON.stringify(data, null, 2));

        // 2. Query Gemini
        const insightText = await generateInsightFromLLM(finalPrompt);

        // 3. Return to Backend
        res.json({ insight: insightText });

    } catch (error) {
        console.error("Controller Error (Insight):", error);
        res.status(500).json({ error: "Failed to generate Insights." });
    }
};
